import pandas as pd
import matplotlib.pyplot as plt
from docx import Document
from docx.shared import Inches

# Step 1: Load the data manually from the document
data = {
    "Run": list(range(1, 31)),
    "Predicted": [
        13.20, 15.98, 16.15, 13.99, 16.72, 13.14, 14.87, 18.08, 17.00, 11.04,
        18.17, 15.72, 19.05, 15.03, 13.55, 15.24, 19.67, 17.92, 13.79, 17.51,
        14.83, 18.88, 13.90, 18.32, 20.95, 22.79, 14.43, 26.16, 14.77, 15.64
    ],
    "Experimental": [
        13.83, 16.05, 16.73, 13.12, 16.16, 13.69, 14.01, 18.87, 17.96, 11.59,
        17.98, 15.19, 18.96, 14.98, 13.23, 15.79, 19.12, 18.09, 13.41, 17.74,
        13.06, 18.54, 13.27, 18.68, 21.04, 23.01, 14.66, 26.70, 14.05, 15.31
    ]
}

df = pd.DataFrame(data)

# Step 2: Plotting
plt.figure(figsize=(10, 6))
plt.plot(df["Run"], df["Predicted"], label="Predicted Yield", marker='o')
plt.plot(df["Run"], df["Experimental"], label="Experimental Yield", marker='x')
plt.title("Predicted vs Experimental Oil Yield from Jatropha Seeds")
plt.xlabel("Run Number")
plt.ylabel("Oil Yield (%)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("yield_comparison.png")
plt.show()

# Step 3: Discussion
discussion = """
The graph compares the predicted oil yield values generated by the Response Surface Methodology (RSM) model 
against the actual experimental results obtained from the Soxhlet extraction of jatropha seeds.

Overall, the predicted values closely follow the experimental trends, indicating that the model has good predictive accuracy. 
The highest experimental yield of 26.70% was recorded at Run 28, which also had the highest predicted yield (26.16%), 
demonstrating strong agreement. Similarly, the lowest yield occurred at Run 10 with 11.59% experimentally and 11.04% predicted.

Minor deviations between predicted and experimental values are observed in some runs, such as Run 3 and Run 7, 
which may be attributed to experimental variability, measurement errors, or limitations in the model's assumptions.

The consistency between predicted and experimental values validates the effectiveness of the Central Composite Rotatable Design 
and the regression model used. This supports the reliability of the optimized parameters for maximizing oil yield from jatropha seeds.
"""

# Step 4: Export to Word
doc = Document()
doc.add_heading("Predicted vs Experimental Oil Yield Analysis", 0)

doc.add_heading("Graphical Comparison", level=1)
doc.add_picture("yield_comparison.png", width=Inches(6))

doc.add_heading("Discussion", level=1)
doc.add_paragraph(discussion)

doc.save("Jatropha_Oil_Yield_Analysis.docx")
